styleguide_name: Epic Game Jam

# Directory to parse
source: drupal/sites/all/themes/epicgamejam/assets

# Directory to build the styleguide
destination: styleguide

# Hologram theme
documentation_assets: bower_components/cortana-two
custom_markdown: bower_components/cortana-two/CortanaMarkdownRenderer.rb

# To have a custom index page build with your README.md
index: README

dependencies:
  - bower_components/jquery/dist
  - drupal/sites/all/themes/epicgamejam/build/js
  - drupal/sites/all/themes/epicgamejam/build/css
  - drupal/sites/all/themes/epicgamejam/build/img
  - drupal/sites/all/themes/epicgamejam/build/fonts

# List all css to include for the styleguide render examples (path from styleguide directory)
css_include:
  - 'css/vendors.css'
  - 'css/main.css'
  - 'css/styleguide.css'

# List all js to include for the styleguide render examples (path from styleguide directory)
js_include:
  - 'dist/jquery.min.js'
  - 'js/vendors.min.js'
  - 'js/main.js'

# String who is used to split the category name and create category wrapper
name_scope: ' - '